[package]
name = "motion-control-playground"
version = "0.1.0"
edition = "2021"
authors = ["Caio Piccirillo <caiopiccirillo@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.1", features = ["serialize"] }
bevy_panorbit_camera = "0.18.0"
bevy_rapier3d = { version = "0.25.0", features = [
   "simd-stable",
    "wasm-bindgen",
] } # "debug-render-3d
bevy-inspector-egui = "0.23.4"
bevy-persistent = { version = "0.5.0", features = ["all"] }
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0"
# bevy_infinite_grid = { git = "https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid", branch = "main" }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[features]
default = ["embedded-model"]
embedded-model = []
blender-model = []
