[package]
name = "motion-control-playground"
version = "0.1.0"
edition = "2021"
authors = ["Caio Piccirillo <caiopiccirillo@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy_panorbit_camera = "0.8.0"
bevy_rapier3d = { version = "0.22.0", features = [ "simd-stable", "wasm-bindgen" ] } # "debug-render-3d
bevy-inspector-egui = "0.20.0" 
bevy_infinite_grid = { git = "https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid", branch = "main" }
